// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><title>Silas's Info Dump</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/styles.css\"><script type=\"text/javascript\" src=\"/static/htmx.min.js\"></script><script src=\"/static/script.js\"></script><style>\n        body {\n            font-family: Arial, Helvetica, sans-serif;\n        }\n    </style></head><body><div class=\"topNav\" hx-boost=\"true\"><a href=\"/\" hx-select=\"#page\" hx-target=\"#page\">Home</a> <a href=\"/articles\" hx-select=\"#page\" hx-target=\"#page\">Articles</a></div><div id=\"page\"><h2>I am still working on this website. To track its progress, visit <a href=\"https://github.com/seesharpsi/silasblog\">github.com/seesharpsi/silasblog</a></h2><div class=\"headshot_box\"><img class=\"headshot\" src=\"/static/headshot.jpg\" alt=\"headshot\"><div class=\"headshot_txt\"><div><div>BS in Software Engineering</div><div>Several years of full-time experience</div><div>Developed apps used by thousands of employees</div><div>Experience with containerized development pipelines</div><div>Extensive use of Python, GoLang, and PHP</div><div>Familiar with Java, C#, and Bash</div></div></div></div></div><div id=\"cookies\">This site doesn't use cookies.<br>(but really, most sites shouldn't) <span class=\"close_cookies_btn\" onclick=\"this.parentElement.style.display='none'\">&times;</span></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
